### ISSUE TITLE
Pre-1.0 checklist

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#392]
Meta issue for discussing what needs to be done before shipping 1.0
- [x] Fix AStar algorithm
- [x] Clean up repo and add setup.py (#293, #179)
- [ ] Fix all bugs that require hitting CTRL-C
- [ ] API-breaking renames (#379, #391)

I know, nobody likes to rename things yet again but when if not before 1.0 do we have the time to clean up this mess of factory/team/simpleteam…

**Comment by otizonaizit** [comment]
What is the status of the AStar thing? Didn't it get fixed last year? If not, shouldn't we fix it **before** releasing on PyPI and use for the tournament?

**Comment by otizonaizit** [comment]
Additionally, I think we should drop python2 support and remove all the compatibility stuff, if we haven't done that yet;-)

**Comment by Debilski** [comment]
Python2: e185518b29708390d1cf8f77431dfd1473f4a7aa

**Comment by Debilski** [comment]
Have 2.0 now.
